// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ClassLibrary.Shared.TestDataGenerator
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Sample")]
    public partial class SampleFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "TestDataGenerator", "Sample", "A short summary of the feature", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "Sample.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Validation messages for a field")]
        public async System.Threading.Tasks.Task ValidationMessagesForAField()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Validation messages for a field", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await testRunner.GivenAsync("Model is selected for the endpoint \"/api/BasicPlanDetails/SaveBasicPlanDetails\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
await testRunner.WhenAsync("the property \"planType\" is configured as \"1\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 9
await testRunner.AndAsync("API request has been sent to the \"IPlanDetailsSave\" with the method name \"CreateN" +
                        "ewPlanAsync\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 10
await testRunner.ThenAsync("API should give response as \"PL143 : Required\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("When multiple properties needs to be changed")]
        public async System.Threading.Tasks.Task WhenMultiplePropertiesNeedsToBeChanged()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("When multiple properties needs to be changed", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 13
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 14
await testRunner.GivenAsync("Vesting model is selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                            "propertyName",
                            "value"});
                table8.AddRow(new string[] {
                            "VestingName",
                            "2 year cliff"});
                table8.AddRow(new string[] {
                            "100% immediate vesting",
                            "No"});
                table8.AddRow(new string[] {
                            "VestingSchedule",
                            "2 Year Cliff"});
#line 15
await testRunner.WhenAsync("Configuration has been made as per following", ((string)(null)), table8, "When ");
#line hidden
#line 20
await testRunner.ThenAsync("API should respond with successful message", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Calculation based scenario")]
        public async System.Threading.Tasks.Task CalculationBasedScenario()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Calculation based scenario", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 24
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 25
await testRunner.GivenAsync("Vesting model is selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table9 = new global::Reqnroll.Table(new string[] {
                            "propertyName",
                            "value"});
                table9.AddRow(new string[] {
                            "VestingName",
                            "2 year cliff"});
                table9.AddRow(new string[] {
                            "100% immediate vesting",
                            "No"});
                table9.AddRow(new string[] {
                            "VestingSchedule",
                            "2 Year Cliff"});
#line 26
await testRunner.WhenAsync("Configuration has been made as per following", ((string)(null)), table9, "When ");
#line hidden
                global::Reqnroll.Table table10 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value"});
                table10.AddRow(new string[] {
                            "HIRE DATE",
                            "01/01/2021"});
                table10.AddRow(new string[] {
                            "HOURS",
                            "1000"});
                table10.AddRow(new string[] {
                            "PAY DATE",
                            "12/01/2021"});
                table10.AddRow(new string[] {
                            "BIRTH DATE",
                            "04/01/1996"});
                table10.AddRow(new string[] {
                            "PAYROLL FREQUENCY",
                            "DemoFrequency"});
#line 31
await testRunner.GivenAsync("Edit payroll file as mentioned below", ((string)(null)), table10, "Given ");
#line hidden
                global::Reqnroll.Table table11 = new global::Reqnroll.Table(new string[] {
                            "creditedThisYear",
                            "computationPeriod",
                            "comments",
                            "vestingYOS",
                            "vestingPercentage",
                            "bisType"});
                table11.AddRow(new string[] {
                            "True",
                            "04-01-2021-03-31-2022",
                            "Participant data changed",
                            "1",
                            "0",
                            ""});
                table11.AddRow(new string[] {
                            "True",
                            "06-01-2021-05-31-2022",
                            "Participant data changed",
                            "2",
                            "0",
                            ""});
                table11.AddRow(new string[] {
                            "False",
                            "06-01-2022-05-31-2023",
                            "Participant data changed",
                            "2",
                            "0",
                            ""});
                table11.AddRow(new string[] {
                            "False",
                            "06-01-2023-05-31-2024",
                            "Participant data changed",
                            "2",
                            "0",
                            ""});
#line 38
await testRunner.ThenAsync("Vesting API should respond as follows", ((string)(null)), table11, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Payroll file")]
        public async System.Threading.Tasks.Task PayrollFile()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Payroll file", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 46
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 47
await testRunner.GivenAsync("Payroll file \"Combined.csv\" is selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table12 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value"});
                table12.AddRow(new string[] {
                            "HIRE DATE",
                            "01/01/2021"});
                table12.AddRow(new string[] {
                            "HOURS",
                            "1000"});
                table12.AddRow(new string[] {
                            "PAY DATE",
                            "12/01/2021"});
                table12.AddRow(new string[] {
                            "BIRTH DATE",
                            "04/01/1996"});
                table12.AddRow(new string[] {
                            "PAYROLL FREQUENCY",
                            "DemoFrequency"});
#line 48
await testRunner.AndAsync("Edit payroll file as mentioned below", ((string)(null)), table12, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Trade order file")]
        public async System.Threading.Tasks.Task TradeOrderFile()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Trade order file", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 57
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 58
await testRunner.GivenAsync("Trade file \"TradeOrder\" is selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table13 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "value"});
                table13.AddRow(new string[] {
                            "CUSIP",
                            "123456789"});
                table13.AddRow(new string[] {
                            "NAV",
                            "2"});
                table13.AddRow(new string[] {
                            "Trade order number",
                            "E12345643452"});
#line 59
await testRunner.AndAsync("Edit Trade file as mentioned below", ((string)(null)), table13, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Reports verification")]
        public async System.Threading.Tasks.Task ReportsVerification()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Reports verification", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 67
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 68
await testRunner.GivenAsync("Eligibility report has been generated for the plan \"Test Plan\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table14 = new global::Reqnroll.Table(new string[] {
                            "ColumnName",
                            "value"});
                table14.AddRow(new string[] {
                            "PlanId",
                            "TP001"});
                table14.AddRow(new string[] {
                            "SSN",
                            "123456789"});
                table14.AddRow(new string[] {
                            "FirstName",
                            "John"});
                table14.AddRow(new string[] {
                            "Eligibility Status",
                            "Eligible"});
                table14.AddRow(new string[] {
                            "Eligibility Date",
                            "01/01/2025"});
                table14.AddRow(new string[] {
                            "Reason",
                            "Immediate Eligibility"});
#line 69
await testRunner.ThenAsync("Report should be displayed as mentioned below", ((string)(null)), table14, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Creating a new employee with payroll file upload")]
        public async System.Threading.Tasks.Task CreatingANewEmployeeWithPayrollFileUpload()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Creating a new employee with payroll file upload", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 80
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 81
await testRunner.GivenAsync("", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
