// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Onboarding.Features.Company
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Company")]
    public partial class CompanyFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Company", "Company", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "Company.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Company name field required validation")]
        public async System.Threading.Tasks.Task CompanyNameFieldRequiredValidation()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Company name field required validation", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
 await testRunner.GivenAsync("Model is selected for the endpoint \"/api/v1/Company\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
 await testRunner.WhenAsync("the property \"name\" is configured as \"\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 9
 await testRunner.AndAsync("API request has been sent to the \"ICompanyDetails\" with the method name \"CreateNe" +
                        "wCompanyAsync\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 10
 await testRunner.ThenAsync("API should give response as \"CM001 : Required\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Company name field positive acceptance")]
        [NUnit.Framework.TestCaseAttribute("abcd", null)]
        [NUnit.Framework.TestCaseAttribute("1234", null)]
        [NUnit.Framework.TestCaseAttribute("!@#$", null)]
        [NUnit.Framework.TestCaseAttribute("abc123", null)]
        [NUnit.Framework.TestCaseAttribute("abc123!@#", null)]
        public async System.Threading.Tasks.Task CompanyNameFieldPositiveAcceptance(string companyName, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("companyName", companyName);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Company name field positive acceptance", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 13
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 14
await testRunner.GivenAsync("Model is selected for the endpoint \"/api/v1/Company\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 15
await testRunner.WhenAsync(string.Format("the property \"name\" is configured as \"{0}\"", companyName), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 16
await testRunner.AndAsync("API request has been sent to the \"ICompanyDetails\" with the method name \"CreateNe" +
                        "wCompanyAsync\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
await testRunner.ThenAsync("API should respond with successful message", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Company name field less than 128 characters")]
        public async System.Threading.Tasks.Task CompanyNameFieldLessThan128Characters()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Company name field less than 128 characters", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 26
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 27
await testRunner.GivenAsync("Model is selected for the endpoint \"/api/v1/Company\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 28
await testRunner.WhenAsync("the property \"name\" is configured with \"alphabets\" with 127 characters", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "key",
                            "value"});
                table1.AddRow(new string[] {
                            "frequencyName",
                            "Daily"});
                table1.AddRow(new string[] {
                            "frequencyType",
                            "1"});
                table1.AddRow(new string[] {
                            "modeOfHours",
                            "1"});
                table1.AddRow(new string[] {
                            "modeOfCompensation",
                            "1"});
                table1.AddRow(new string[] {
                            "modeOfContribution",
                            "1"});
                table1.AddRow(new string[] {
                            "employeeClassificationType",
                            "1"});
                table1.AddRow(new string[] {
                            "code",
                            "L1"});
                table1.AddRow(new string[] {
                            "classificationName",
                            "Location"});
#line 29
await testRunner.AndAsync("Configuration has been done as mentioned below", ((string)(null)), table1, "And ");
#line hidden
#line 39
await testRunner.AndAsync("API request has been sent to the \"ICompanyDetails\" with the method name \"CreateNe" +
                        "wCompanyAsync\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 40
await testRunner.ThenAsync("API should respond with successful message", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Company name field equal to 128 characters")]
        public async System.Threading.Tasks.Task CompanyNameFieldEqualTo128Characters()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Company name field equal to 128 characters", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 42
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 43
await testRunner.GivenAsync("Model is selected for the endpoint \"/api/v1/Company\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 44
await testRunner.WhenAsync("the property \"name\" is configured with \"alphabets\" with 128 characters", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 45
await testRunner.AndAsync("API request has been sent to the \"ICompanyDetails\" with the method name \"CreateNe" +
                        "wCompanyAsync\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 46
await testRunner.ThenAsync("API should respond with successful message", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Company name field more than 128 characters")]
        public async System.Threading.Tasks.Task CompanyNameFieldMoreThan128Characters()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Company name field more than 128 characters", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 48
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 49
await testRunner.GivenAsync("Model is selected for the endpoint \"/api/v1/Company\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 50
await testRunner.WhenAsync("the property \"name\" is configured with \"alphabets\" with 129 characters", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 51
await testRunner.AndAsync("API request has been sent to the \"ICompanyDetails\" with the method name \"CreateNe" +
                        "wCompanyAsync\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 52
await testRunner.ThenAsync("API should give response as \"CM002 : Company name length should not exceed 128 ch" +
                        "aracters.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Address 1 field positive acceptance")]
        [NUnit.Framework.TestCaseAttribute("abcd", null)]
        [NUnit.Framework.TestCaseAttribute("1234", null)]
        [NUnit.Framework.TestCaseAttribute("!@#$", null)]
        [NUnit.Framework.TestCaseAttribute("abc123", null)]
        [NUnit.Framework.TestCaseAttribute("abc123!@#", null)]
        public async System.Threading.Tasks.Task Address1FieldPositiveAcceptance(string address1, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("address1", address1);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Address 1 field positive acceptance", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 54
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 55
await testRunner.GivenAsync("Model is selected for the endpoint \"/api/v1/Company\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 56
await testRunner.WhenAsync(string.Format("the property \"name\" is configured as \"{0}\"", address1), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 57
await testRunner.AndAsync("API request has been sent to the \"ICompanyDetails\" with the method name \"CreateNe" +
                        "wCompanyAsync\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 58
await testRunner.ThenAsync("API should respond with successful message", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Address 1 field less than 100 characters")]
        public async System.Threading.Tasks.Task Address1FieldLessThan100Characters()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Address 1 field less than 100 characters", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 67
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 68
await testRunner.GivenAsync("Model is selected for the endpoint \"/api/v1/Company\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 69
await testRunner.WhenAsync("the property \"address1\" is configured with \"alphabets\" with 99 characters", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 70
await testRunner.AndAsync("API request has been sent to the \"ICompanyDetails\" with the method name \"CreateNe" +
                        "wCompanyAsync\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 71
await testRunner.ThenAsync("API should respond with successful message", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Address 1 field equal to 100 characters")]
        public async System.Threading.Tasks.Task Address1FieldEqualTo100Characters()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Address 1 field equal to 100 characters", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 73
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 74
await testRunner.GivenAsync("Model is selected for the endpoint \"/api/v1/Company\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 75
await testRunner.WhenAsync("the property \"address1\" is configured with \"alphabets\" with 100 characters", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 76
await testRunner.AndAsync("API request has been sent to the \"ICompanyDetails\" with the method name \"CreateNe" +
                        "wCompanyAsync\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 77
await testRunner.ThenAsync("API should respond with successful message", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Address 1 field more than 128 characters")]
        public async System.Threading.Tasks.Task Address1FieldMoreThan128Characters()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Address 1 field more than 128 characters", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 79
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 80
await testRunner.GivenAsync("Model is selected for the endpoint \"/api/v1/Company\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 81
await testRunner.WhenAsync("the property \"address1\" is configured with \"alphabets\" with 101 characters", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 82
await testRunner.AndAsync("API request has been sent to the \"ICompanyDetails\" with the method name \"CreateNe" +
                        "wCompanyAsync\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 83
await testRunner.ThenAsync("API should give response as \"CM004 : Address 1 length should not exceed 100 chara" +
                        "cters.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Address 2 field positive acceptance")]
        [NUnit.Framework.TestCaseAttribute("abcd", null)]
        [NUnit.Framework.TestCaseAttribute("1234", null)]
        [NUnit.Framework.TestCaseAttribute("!@#$", null)]
        [NUnit.Framework.TestCaseAttribute("abc123", null)]
        [NUnit.Framework.TestCaseAttribute("abc123!@#", null)]
        public async System.Threading.Tasks.Task Address2FieldPositiveAcceptance(string address2, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("address2", address2);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Address 2 field positive acceptance", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 86
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 87
await testRunner.GivenAsync("Model is selected for the endpoint \"/api/v1/Company\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 88
await testRunner.WhenAsync(string.Format("the property \"name\" is configured as \"{0}\"", address2), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 89
await testRunner.AndAsync("API request has been sent to the \"ICompanyDetails\" with the method name \"CreateNe" +
                        "wCompanyAsync\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 90
await testRunner.ThenAsync("API should respond with successful message", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Address 2 field less than 100 characters")]
        public async System.Threading.Tasks.Task Address2FieldLessThan100Characters()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Address 2 field less than 100 characters", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 99
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 100
await testRunner.GivenAsync("Model is selected for the endpoint \"/api/v1/Company\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 101
await testRunner.WhenAsync("the property \"address2\" is configured with \"alphabets\" with 99 characters", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 102
await testRunner.AndAsync("API request has been sent to the \"ICompanyDetails\" with the method name \"CreateNe" +
                        "wCompanyAsync\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 103
await testRunner.ThenAsync("API should respond with successful message", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Address 2 field equal to 100 characters")]
        public async System.Threading.Tasks.Task Address2FieldEqualTo100Characters()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Address 2 field equal to 100 characters", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 105
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 106
await testRunner.GivenAsync("Model is selected for the endpoint \"/api/v1/Company\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 107
await testRunner.WhenAsync("the property \"address2\" is configured with \"alphabets\" with 100 characters", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 108
await testRunner.AndAsync("API request has been sent to the \"ICompanyDetails\" with the method name \"CreateNe" +
                        "wCompanyAsync\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 109
await testRunner.ThenAsync("API should respond with successful message", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Address 2 field more than 128 characters")]
        public async System.Threading.Tasks.Task Address2FieldMoreThan128Characters()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Address 2 field more than 128 characters", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 111
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 112
await testRunner.GivenAsync("Model is selected for the endpoint \"/api/v1/Company\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 113
await testRunner.WhenAsync("the property \"address2\" is configured with \"alphabets\" with 101 characters", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 114
await testRunner.AndAsync("API request has been sent to the \"ICompanyDetails\" with the method name \"CreateNe" +
                        "wCompanyAsync\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 115
await testRunner.ThenAsync("API should give response as \"CM004 : Address 1 length should not exceed 100 chara" +
                        "cters.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("City field positive acceptance")]
        [NUnit.Framework.TestCaseAttribute("abcd", null)]
        [NUnit.Framework.TestCaseAttribute("1234", null)]
        [NUnit.Framework.TestCaseAttribute("!@#$", null)]
        [NUnit.Framework.TestCaseAttribute("abc123", null)]
        [NUnit.Framework.TestCaseAttribute("abc123!@#", null)]
        public async System.Threading.Tasks.Task CityFieldPositiveAcceptance(string city, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("city", city);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("City field positive acceptance", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 118
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 119
await testRunner.GivenAsync("Model is selected for the endpoint \"/api/v1/Company\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 120
await testRunner.WhenAsync(string.Format("the property \"name\" is configured as \"{0}\"", city), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 121
await testRunner.AndAsync("API request has been sent to the \"ICompanyDetails\" with the method name \"CreateNe" +
                        "wCompanyAsync\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 122
await testRunner.ThenAsync("API should respond with successful message", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("City field less than 30 characters")]
        public async System.Threading.Tasks.Task CityFieldLessThan30Characters()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("City field less than 30 characters", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 131
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 132
await testRunner.GivenAsync("Model is selected for the endpoint \"/api/v1/Company\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 133
await testRunner.WhenAsync("the property \"city\" is configured with \"alphabets\" with 29 characters", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 134
await testRunner.AndAsync("API request has been sent to the \"ICompanyDetails\" with the method name \"CreateNe" +
                        "wCompanyAsync\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 135
await testRunner.ThenAsync("API should respond with successful message", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("City field equal to 30 characters")]
        public async System.Threading.Tasks.Task CityFieldEqualTo30Characters()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("City field equal to 30 characters", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 137
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 138
await testRunner.GivenAsync("Model is selected for the endpoint \"/api/v1/Company\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 139
await testRunner.WhenAsync("the property \"city\" is configured with \"alphabets\" with 30 characters", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 140
await testRunner.AndAsync("API request has been sent to the \"ICompanyDetails\" with the method name \"CreateNe" +
                        "wCompanyAsync\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 141
await testRunner.ThenAsync("API should respond with successful message", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("City field more than 30 characters")]
        public async System.Threading.Tasks.Task CityFieldMoreThan30Characters()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("City field more than 30 characters", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 143
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 144
await testRunner.GivenAsync("Model is selected for the endpoint \"/api/v1/Company\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 145
await testRunner.WhenAsync("the property \"city\" is configured with \"alphabets\" with 31 characters", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 146
await testRunner.AndAsync("API request has been sent to the \"ICompanyDetails\" with the method name \"CreateNe" +
                        "wCompanyAsync\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 147
await testRunner.ThenAsync("API should give response as \"CM004 : Address 1 length should not exceed 100 chara" +
                        "cters.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Company model with multiple properties configured")]
        public async System.Threading.Tasks.Task CompanyModelWithMultiplePropertiesConfigured()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Company model with multiple properties configured", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 177
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 178
await testRunner.GivenAsync("Model is selected for the endpoint \"/api/v1/Company\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "propertyName",
                            "value"});
                table2.AddRow(new string[] {
                            "name",
                            ""});
                table2.AddRow(new string[] {
                            "postalCode",
                            "abced"});
                table2.AddRow(new string[] {
                            "taxEIN",
                            ""});
#line 179
await testRunner.WhenAsync("Configuration has been made as per following", ((string)(null)), table2, "When ");
#line hidden
#line 184
await testRunner.AndAsync("API request has been sent to the \"ICompanyDetails\" with the method name \"CreateNe" +
                        "wCompanyAsync\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 185
await testRunner.ThenAsync("API should give response as \"CM001 : Required\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
