// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Payroll.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Payroll")]
    public partial class PayrollFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Payroll", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "Payroll.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Payroll file upload for an active plan")]
        [NUnit.Framework.CategoryAttribute("PlanActivation")]
        public async System.Threading.Tasks.Task PayrollFileUploadForAnActivePlan()
        {
            string[] tagsOfScenario = new string[] {
                    "PlanActivation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Payroll file upload for an active plan", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await testRunner.GivenAsync("Model is selected for the endpoint \"/api/Loan/SaveLoan\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table222 = new global::Reqnroll.Table(new string[] {
                            "propertyName",
                            "value"});
                table222.AddRow(new string[] {
                            "loanType",
                            "1"});
                table222.AddRow(new string[] {
                            "numberOfLoansAllowed",
                            "5"});
                table222.AddRow(new string[] {
                            "loanPerPlanYear",
                            "3"});
                table222.AddRow(new string[] {
                            "minimumAmount",
                            "10"});
                table222.AddRow(new string[] {
                            "processingTimeForLoan",
                            "10"});
                table222.AddRow(new string[] {
                            "waitingPeriodBetweenLoansPayoffAndLoanRequest",
                            "10"});
                table222.AddRow(new string[] {
                            "numberOfSuspensionsPerLoanAllowed",
                            "1"});
                table222.AddRow(new string[] {
                            "checkFee",
                            "2"});
                table222.AddRow(new string[] {
                            "overnightDeliveryFees",
                            "1"});
                table222.AddRow(new string[] {
                            "maximumAmount",
                            "1"});
                table222.AddRow(new string[] {
                            "withdrawalBasis",
                            "1"});
                table222.AddRow(new string[] {
                            "refinancingAllowed",
                            "false"});
                table222.AddRow(new string[] {
                            "curePeriod",
                            "1"});
                table222.AddRow(new string[] {
                            "curePeriodForEmployeeTermination",
                            "1"});
                table222.AddRow(new string[] {
                            "defaultMethod",
                            "1"});
                table222.AddRow(new string[] {
                            "minimumLoanRepaymentAmount",
                            "10"});
                table222.AddRow(new string[] {
                            "loanApportioningMethod",
                            "1"});
                table222.AddRow(new string[] {
                            "loanInterestRate",
                            "1"});
                table222.AddRow(new string[] {
                            "loanFeeAmount",
                            "5"});
                table222.AddRow(new string[] {
                            "minimumLengthYears",
                            "1"});
                table222.AddRow(new string[] {
                            "minimumLengthMonths",
                            "0"});
                table222.AddRow(new string[] {
                            "maximumLengthYears",
                            "5"});
                table222.AddRow(new string[] {
                            "maximumLengthMonths",
                            "0"});
                table222.AddRow(new string[] {
                            "firstRepaymentDateFallsAfter",
                            "20"});
                table222.AddRow(new string[] {
                            "firstRepaymentDateFallsWithin",
                            "25"});
                table222.AddRow(new string[] {
                            "masterLoanTypeId",
                            "1"});
                table222.AddRow(new string[] {
                            "isMaster",
                            "true"});
                table222.AddRow(new string[] {
                            "loanDescription",
                            "General Purpose"});
#line 8
await testRunner.WhenAsync("Configuration has been made as per following", ((string)(null)), table222, "When ");
#line hidden
#line 39
await testRunner.AndAsync("Save Loan details in Plan", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table223 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value"});
                table223.AddRow(new string[] {
                            "HIRE DATE",
                            "01/01/2025"});
                table223.AddRow(new string[] {
                            "HOURS",
                            "1000"});
                table223.AddRow(new string[] {
                            "PAY DATE",
                            "02/01/2025"});
                table223.AddRow(new string[] {
                            "BIRTH DATE",
                            "04/01/1996"});
                table223.AddRow(new string[] {
                            "PAYROLL FREQUENCY",
                            "Daily"});
                table223.AddRow(new string[] {
                            "Pretax",
                            "100"});
#line 41
await testRunner.GivenAsync("Payroll file \"CombinedFile.csv\" is selected and Edit payroll file as mentioned be" +
                        "low", ((string)(null)), table223, "Given ");
#line hidden
#line 50
await testRunner.WhenAsync("File upload is executed for the file \"CombinedFile.csv\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table224 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value"});
                table224.AddRow(new string[] {
                            "Order Number",
                            ""});
#line 52
await testRunner.GivenAsync("Payroll file \"TradeOrder.csv\" is selected and Edit payroll file as mentioned belo" +
                        "w", ((string)(null)), table224, "Given ");
#line hidden
#line 56
await testRunner.WhenAsync("File upload is executed for the file \"TradeOrder.csv\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 58
await testRunner.GivenAsync("Model is selected for the endpoint \"/api/v1/Loan/SaveInprogressLoanRequest\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table225 = new global::Reqnroll.Table(new string[] {
                            "propertyName",
                            "value"});
                table225.AddRow(new string[] {
                            "loanType",
                            "General Purpose"});
                table225.AddRow(new string[] {
                            "interestRate",
                            "6"});
                table225.AddRow(new string[] {
                            "requestedAmount",
                            "20"});
                table225.AddRow(new string[] {
                            "periodicPaymentAmount",
                            "2"});
                table225.AddRow(new string[] {
                            "paymentMethod",
                            "1"});
                table225.AddRow(new string[] {
                            "repaymentMethod",
                            "1"});
                table225.AddRow(new string[] {
                            "firstRepaymentDate",
                            "3/1/2025, 12:00:00 AM"});
                table225.AddRow(new string[] {
                            "repaymentFrequency",
                            "1"});
                table225.AddRow(new string[] {
                            "tenureYears",
                            "1"});
                table225.AddRow(new string[] {
                            "tenureMonths",
                            "0"});
                table225.AddRow(new string[] {
                            "loanStatus",
                            "3"});
#line 60
await testRunner.WhenAsync("Configuration has been made as per following", ((string)(null)), table225, "When ");
#line hidden
#line 74
await testRunner.AndAsync("API request has been sent to the \"ILoan\" with the method name \"SaveInprogressLoan" +
                        "Request\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 76
await testRunner.AndAsync("Loan request has been approved and trade for loan is executed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table226 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value"});
                table226.AddRow(new string[] {
                            "Order Number",
                            ""});
#line 78
await testRunner.GivenAsync("Payroll file \"TradeOrder.csv\" is selected and Edit payroll file as mentioned belo" +
                        "w", ((string)(null)), table226, "Given ");
#line hidden
#line 82
await testRunner.WhenAsync("File upload is executed for the file \"TradeOrder.csv\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Employee save through payroll file upload")]
        [NUnit.Framework.CategoryAttribute("SaveEmployee")]
        public async System.Threading.Tasks.Task EmployeeSaveThroughPayrollFileUpload()
        {
            string[] tagsOfScenario = new string[] {
                    "SaveEmployee"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Employee save through payroll file upload", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 85
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
